[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ezshutdown"
version = "0.1.0"
description = "A simple CLI shutdown timer for Windows, written in Python."
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [
    { name = "Kai Sinz" }
]
dependencies = []

[project.scripts]
ezshutdown = "ezshutdown.cli:main"
ezshut = "ezshutdown.cli:main"
ezsh = "ezshutdown.cli:main"

[project.urls]
Homepage = "https://github.com/k-sinz/ezshutdown"
